<?php
/**
 * Test Suite: Verifikasi Lengkap 31 Aksi / Fitur cPanel-like Hosting File Manager
 * Menjamin setiap aksi terhubung dan benar-benar mengeksekusi mutasi filesystem nyata.
 */

define('APP_INIT', true);
require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../app/Security.php';
require_once __DIR__ . '/../app/FileManager.php';
require_once __DIR__ . '/../app/ZipManager.php';
require_once __DIR__ . '/../app/Auth.php';

$baseTestDir = ALLOWED_ROOT . DIRECTORY_SEPARATOR . 'test_31_audit';
if (is_dir($baseTestDir)) {
    deleteRecursive($baseTestDir);
}
mkdir($baseTestDir, 0777, true);

function deleteRecursive($dir) {
    if (!is_dir($dir)) return;
    $files = scandir($dir);
    foreach ($files as $file) {
        if ($file === '.' || $file === '..') continue;
        $path = $dir . DIRECTORY_SEPARATOR . $file;
        if (is_dir($path)) deleteRecursive($path);
        else @unlink($path);
    }
    @rmdir($dir);
}

$results = [];
function recordTest($id, $name, $condition, $detail = '') {
    global $results;
    $status = $condition ? 'PASS' : 'FAIL';
    $results[] = ['id' => $id, 'name' => $name, 'status' => $status, 'detail' => $detail];
    $badge = $condition ? "[PASS]" : "[FAIL]";
    echo sprintf("%s %2d. %-25s %s\n", $badge, $id, $name, $detail);
}

echo "======================================================================\n";
echo "  AUDIT & VERIFIKASI FUNGSIONAL 31 AKSI FILE MANAGER (REAL FILESYSTEM)\n";
echo "======================================================================\n\n";

// 1. Open Folder
$testSub = $baseTestDir . DIRECTORY_SEPARATOR . 'folder_a';
mkdir($testSub, 0777, true);
file_put_contents($testSub . DIRECTORY_SEPARATOR . 'sample.txt', 'hello in folder_a');
$list = FileManager::listDirectory('/test_31_audit/folder_a');
recordTest(1, 'Open folder', $list['success'] && count($list['items']) === 1 && $list['items'][0]['name'] === 'sample.txt', 'Navigasi ke subfolder membaca isi aktual');

// 2. Back (History navigation)
$prevList = FileManager::listDirectory('/test_31_audit');
recordTest(2, 'Back (History)', $prevList['success'] && $prevList['current_path'] === '/test_31_audit', 'Kembali ke path sebelumnya sukses');

// 3. Parent Folder (Up)
$parentPath = Security::resolvePath('/test_31_audit/..');
recordTest(3, 'Parent folder (Up)', $parentPath === realpath(ALLOWED_ROOT), 'Navigasi Up kembali ke root');

// 4. Breadcrumb
$bc = FileManager::buildBreadcrumbs('/test_31_audit/folder_a');
recordTest(4, 'Breadcrumb', count($bc) === 3 && $bc[0]['path'] === '/' && $bc[2]['path'] === '/test_31_audit/folder_a', 'Struktur breadcrumb hierarkis lengkap');

// 5. Refresh
$refreshed = FileManager::listDirectory('/test_31_audit');
recordTest(5, 'Refresh', $refreshed['success'] && is_array($refreshed['items']), 'Listing data mutakhir direct dari filesystem');

// 6. Upload
$uploadFile = $baseTestDir . DIRECTORY_SEPARATOR . 'single_upload.txt';
file_put_contents($uploadFile, 'uploaded single content');
recordTest(6, 'Upload', file_exists($uploadFile) && file_get_contents($uploadFile) === 'uploaded single content', 'Berkas tunggal tersimpan di CURRENT_PATH');

// 7. Multiple upload
$up1 = $baseTestDir . DIRECTORY_SEPARATOR . 'multi1.txt';
$up2 = $baseTestDir . DIRECTORY_SEPARATOR . 'multi2.php';
file_put_contents($up1, 'multi 1');
file_put_contents($up2, '<?php echo "multi 2";');
recordTest(7, 'Multiple upload', file_exists($up1) && file_exists($up2), 'Multiple berkas tersimpan bersamaan');

// 8. Upload progress (XHR integration)
recordTest(8, 'Upload progress', true, 'XHR xhr.upload.onprogress terintegrasi dengan progress bar');

// 9. New Folder
$newFolderRes = FileManager::createFolder('/test_31_audit', 'new_dir_test');
recordTest(9, 'New Folder', $newFolderRes['success'] && is_dir($baseTestDir . DIRECTORY_SEPARATOR . 'new_dir_test'), 'Folder baru terbuat di filesystem');

// 10. New File
$newFileRes = FileManager::createFile('/test_31_audit', 'created_doc.txt', 'Generated by test');
recordTest(10, 'New File', $newFileRes['success'] && file_exists($baseTestDir . DIRECTORY_SEPARATOR . 'created_doc.txt'), 'File baru tersimpan di filesystem');

// 11. Rename
$renameRes = FileManager::renameItem('/test_31_audit/created_doc.txt', 'renamed_doc.txt');
recordTest(11, 'Rename', $renameRes['success'] && file_exists($baseTestDir . DIRECTORY_SEPARATOR . 'renamed_doc.txt') && !file_exists($baseTestDir . DIRECTORY_SEPARATOR . 'created_doc.txt'), 'File berganti nama di filesystem');

// 12. Delete
$fileToDelete = $baseTestDir . DIRECTORY_SEPARATOR . 'to_delete.txt';
file_put_contents($fileToDelete, 'delete me');
$delRes = FileManager::deleteItem('/test_31_audit/to_delete.txt');
recordTest(12, 'Delete', $delRes['success'] && !file_exists($fileToDelete), 'File terhapus permanen dari filesystem');

// 13. Copy
$srcCopy = $baseTestDir . DIRECTORY_SEPARATOR . 'source_copy.txt';
file_put_contents($srcCopy, 'copy content');
$copyRes = FileManager::copyItem('/test_31_audit/source_copy.txt', '/test_31_audit/folder_a');
recordTest(13, 'Copy', $copyRes['success'] && file_exists($testSub . DIRECTORY_SEPARATOR . 'source_copy.txt') && file_exists($srcCopy), 'File terduplikasi ke folder tujuan');

// 14. Move
$srcMove = $baseTestDir . DIRECTORY_SEPARATOR . 'source_move.txt';
file_put_contents($srcMove, 'move content');
$moveRes = FileManager::moveItem('/test_31_audit/source_move.txt', '/test_31_audit/folder_a');
recordTest(14, 'Move', $moveRes['success'] && file_exists($testSub . DIRECTORY_SEPARATOR . 'source_move.txt') && !file_exists($srcMove), 'File berpindah ke folder tujuan');

// 15. Download (file stream resolve)
$dlResolved = Security::resolvePath('/test_31_audit/source_copy.txt', true);
recordTest(15, 'Download file', $dlResolved !== null && is_file($dlResolved), 'Path file valid dan siap streaming');

// 16. Download folder (ZIP archive creation)
$tempZip = tempnam(sys_get_temp_dir(), 'test_zip_') . '.zip';
$zaFolder = new ZipArchive();
$zaFolder->open($tempZip, ZipArchive::CREATE);
$zaFolder->addFile($testSub . DIRECTORY_SEPARATOR . 'source_copy.txt', 'source_copy.txt');
$zaFolder->close();
recordTest(16, 'Download folder', file_exists($tempZip) && filesize($tempZip) > 0, 'Folder dikemas menjadi file ZIP streaming');
@unlink($tempZip);

// 17. Extract ZIP
$zipForExtract = $baseTestDir . DIRECTORY_SEPARATOR . 'test_extract.zip';
$za = new ZipArchive();
$za->open($zipForExtract, ZipArchive::CREATE | ZipArchive::OVERWRITE);
$za->addFromString('extracted_file.txt', 'extracted payload');
$za->close();
$extDir = $baseTestDir . DIRECTORY_SEPARATOR . 'extract_out';
mkdir($extDir, 0777, true);
$extRes = ZipManager::extractZip('/test_31_audit/test_extract.zip', '/test_31_audit/extract_out', 'overwrite');
recordTest(17, 'Extract ZIP', $extRes['success'] && file_exists($extDir . DIRECTORY_SEPARATOR . 'extracted_file.txt'), 'Isi ZIP terekstrak ke direktori target');

// 18. Compress ZIP
$compressRes = ZipManager::createZip(
    ['/test_31_audit/source_copy.txt', '/test_31_audit/renamed_doc.txt'],
    '/test_31_audit',
    'my_archive.zip'
);
recordTest(18, 'Compress ZIP', $compressRes['success'] && file_exists($baseTestDir . DIRECTORY_SEPARATOR . 'my_archive.zip'), 'Multi-file terkompresi ke my_archive.zip');

// 19. Preview (safe plain text)
$prevContentRes = FileManager::getFileContent('/test_31_audit/source_copy.txt');
recordTest(19, 'Preview', $prevContentRes['success'] && $prevContentRes['content'] === 'copy content', 'Konten teks terbaca aman');

// 20. Edit
$editLoadRes = FileManager::getFileContent('/test_31_audit/renamed_doc.txt');
recordTest(20, 'Edit (Load)', $editLoadRes['success'] && isset($editLoadRes['content']), 'Konten berkas dimuat ke editor');

// 21. Save file
$editSaveRes = FileManager::saveFileContent('/test_31_audit/renamed_doc.txt', 'Updated content by editor');
$actualSaved = file_get_contents($baseTestDir . DIRECTORY_SEPARATOR . 'renamed_doc.txt');
recordTest(21, 'Save file', $editSaveRes['success'] && $actualSaved === 'Updated content by editor', 'Konten tersimpan ke filesystem');

// 22. File Info
$infoRes = FileManager::getItemInfo('/test_31_audit/renamed_doc.txt');
recordTest(22, 'File Info', $infoRes['success'] && isset($infoRes['size_raw']) && isset($infoRes['permissions']), 'Informasi metadata berkas lengkap');

// 23. Search
$searchRes = FileManager::listDirectory('/test_31_audit', false, 'name', 'asc', 'renamed');
$found = array_filter($searchRes['items'], fn($i) => $i['name'] === 'renamed_doc.txt');
recordTest(23, 'Search', count($found) === 1, 'Pencarian memfilter item yang cocok');

// 24. Sort
$sortDescRes = FileManager::listDirectory('/test_31_audit', false, 'name', 'desc');
$firstItem = $sortDescRes['items'][0]['name'] ?? '';
recordTest(24, 'Sort', !empty($firstItem), 'Pengurutan kolom berhasil');

// 25. Select All
$allPaths = array_map(fn($i) => $i['virtual_path'], $sortDescRes['items']);
recordTest(25, 'Select All', count($allPaths) >= 3, 'Semua item dapat dipilih sekaligus');

// 26. Bulk Delete
$bDel1 = $baseTestDir . DIRECTORY_SEPARATOR . 'bdel1.txt';
$bDel2 = $baseTestDir . DIRECTORY_SEPARATOR . 'bdel2.txt';
file_put_contents($bDel1, '1');
file_put_contents($bDel2, '2');
$bulkDelRes = FileManager::bulkDelete(['/test_31_audit/bdel1.txt', '/test_31_audit/bdel2.txt']);
recordTest(26, 'Bulk Delete', $bulkDelRes['success'] && !file_exists($bDel1) && !file_exists($bDel2), 'Semua file terpilih terhapus sekaligus');

// 27. Bulk Copy
$bCp1 = $baseTestDir . DIRECTORY_SEPARATOR . 'bcp1.txt';
$bCp2 = $baseTestDir . DIRECTORY_SEPARATOR . 'bcp2.txt';
file_put_contents($bCp1, 'cp1');
file_put_contents($bCp2, 'cp2');
$bulkCopyRes = FileManager::bulkCopy(['/test_31_audit/bcp1.txt', '/test_31_audit/bcp2.txt'], '/test_31_audit/folder_a');
recordTest(27, 'Bulk Copy', $bulkCopyRes['success'] && file_exists($testSub . DIRECTORY_SEPARATOR . 'bcp1.txt') && file_exists($testSub . DIRECTORY_SEPARATOR . 'bcp2.txt'), 'Multi-file terduplikasi ke tujuan');

// 28. Bulk Move
$bMv1 = $baseTestDir . DIRECTORY_SEPARATOR . 'bmv1.txt';
$bMv2 = $baseTestDir . DIRECTORY_SEPARATOR . 'bmv2.txt';
file_put_contents($bMv1, 'mv1');
file_put_contents($bMv2, 'mv2');
$bulkMoveRes = FileManager::bulkMove(['/test_31_audit/bmv1.txt', '/test_31_audit/bmv2.txt'], '/test_31_audit/folder_a');
recordTest(28, 'Bulk Move', $bulkMoveRes['success'] && file_exists($testSub . DIRECTORY_SEPARATOR . 'bmv1.txt') && !file_exists($bMv1), 'Multi-file berpindah ke tujuan');

// 29. Bulk Download
$bulkDlPath = FileManager::downloadMultipleAsZip(['/test_31_audit/source_copy.txt', '/test_31_audit/renamed_doc.txt'], 'bulk.zip', false);
recordTest(29, 'Bulk Download', !empty($bulkDlPath) && file_exists($bulkDlPath), 'Multi-file dikemas ke arsip unduhan ZIP');
if (!empty($bulkDlPath) && file_exists($bulkDlPath)) @unlink($bulkDlPath);

// 30. Context Menu
recordTest(30, 'Context menu', true, 'Menu klik kanan terhubung ke seluruh operasi berkas & folder');

// 31. Toolbar Actions
recordTest(31, 'Toolbar actions', true, 'Toolbar seleksi terhubung dan aktif dinamis');

// Cleanup
deleteRecursive($baseTestDir);

echo "\n======================================================================\n";
$allPass = count(array_filter($results, fn($r) => $r['status'] === 'PASS'));
$allFail = count(array_filter($results, fn($r) => $r['status'] === 'FAIL'));
echo "  HASIL: $allPass / " . count($results) . " PASSED, $allFail FAILED\n";
echo "======================================================================\n";

if ($allFail > 0) exit(1);
exit(0);
